### ISSUE TITLE
Commerce: Loading catalog root and catalogs crash when changing request culture

### ISSUE THREAD

**Issue by stefanolsen** [episerver/netcore-preview#121]
I have a piece of code that overrides `RequestCultureProvider` to change the culture based on some parameters. This is generally fine.

But when using certain cultures, for instance Norwegian, the `ContentReference.Parse` method crashes for catalog root and catalogs, because of the prepended minus-sign. This causes browsing of the Commerce catalog to crash, but does not impact browsing categories or entries by direct link.

After a lot of debugging, it turns out that the `ContentReference.TryParse` method parses the content ID using the `int.TryParse` method, which by default uses the current culture. But in Norwegian the `NumberFormatInfo.NegativeSign` is slightly different from the one used in `NumberFormatInfo.InvariantInfo`.

Please update the `ContentReference.TryParse` to use the int.TryParse overload with `NumberFormatInfo.InvariantInfo`, explicitly.

Builds:
- EPiServer.CMS.Core: 12.0.2
- EPiServer.CMS.UI.Core: 12.0.2-pre-022463

**Comment by stefanolsen** [comment]
@jbearfoot: Will this be a minor fix?

**Comment by jbearfoot** [comment]
Is there a repro step that I can apply? Would it be like: 
CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("no");
ContentReference.TryParse("what does your string look like", out var _);

**Comment by stefanolsen** [comment]
Register this culture provider in Startup (code is simplified for this sample):
```
public class HostCultureProvider : RequestCultureProvider
{
    public override Task<ProviderCultureResult> DetermineProviderCultureResult(HttpContext httpContext)
    {
        var culture = CultureInfo.GetCultureInfo("no");

        return Task.FromResult(new ProviderCultureResult(culture.Name, culture.Name));
    }
}
```

Put this in a controller action (or anywhere else where it is easy to invoke it):
```
var id = "-1073741823__CatalogContent";
var contentRef = ContentReference.Parse(id);
```

Alternatively, just browse `/Episerver/Commerce/Catalog`. It should load the catalog root, but fails because `ContentReferenceConverter` calls `ContentReference.Parse` internally.

**Comment by mrahl** [comment]
@stefanolsen a preview version of CMS Core 12.0.3-pre-020807 was published on the beta feed containing a fix for this. Please confirm if this version solves the issue.

Note: There's also a change to PartialContentComponent in this version, so you will need to change any viewcomponents to override the protected InvokeComponent instead of the public Invoke method.

**Comment by stefanolsen** [comment]
@jbearfoot @mrahl

It fixed a lot. But this related error started showing:
```
System.AggregateException: One or more errors occurred. (Given uri 'content:CatalogContent/âˆ’1073741823/' is not a content uri)
 ---> System.FormatException: Given uri 'content:CatalogContent/âˆ’1073741823/' is not a content uri
   at EPiServer.Approvals.ContentApprovals.Internal.ContentApprovalReferenceHelper.GetContentReference(Uri key, Boolean throwOnNonContent)
   at EPiServer.Approvals.ContentApprovals.Internal.ContentApprovalDefinitionReferenceResolver.ResolveAsync(Uri reference)
   at EPiServer.Approvals.Internal.DefaultApprovalDefinitionRepository.ResolveAsync(Uri reference)
   at EPiServer.Cms.Shell.UI.Rest.Approvals.ApprovalService.HasDefinitionAndIsEnabledAsync(ContentReference contentLink)
   at EPiServer.Cms.Shell.UI.Rest.StatusTransition.StatusTransitionService.HasApprovalDefinition(ContentReference contentLink)
   at EPiServer.Cms.Shell.UI.Rest.StatusTransition.StatusTransitionService.GetTransitionsAsync(IContent content, IPrincipal principal, CultureInfo preferredCulture)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at EPiServer.Cms.Shell.UI.Rest.Models.Transforms.Internal.ContentDataStoreModelTransform.TransformInstance(IContent source, ContentDataStoreModel target, IModelTransformContext context)
   at EPiServer.Cms.Shell.UI.Rest.Models.Transforms.TransformBase`1.Execute(IEnumerable`1 items)+MoveNext()
   at EPiServer.Cms.Shell.UI.Rest.Models.Transforms.TransformBase`1.Execute(IEnumerable`1 items)+MoveNext()
   at EPiServer.Cms.Shell.UI.Rest.Models.Transforms.TransformBase`1.Execute(IEnumerable`1 items)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at EPiServer.Cms.Shell.UI.Rest.ContentStoreModelCreatorExtensions.CreateContentDataStoreModel[TModel](IContentStoreModelCreator contentStoreModelCreator, IContent content, DefaultQueryParameters queryParameters)
   at EPiServer.Cms.Shell.UI.Rest.Internal.ContentDataStore.<>c__DisplayClass9_0.<GetContent>b__0(IContent content)
   at EPiServer.Cms.Shell.UI.Rest.Internal.RestStatusUtil.ExecuteWithSecurityCheck[T](ContentReference contentLink, IContentLoader contentLoader, AccessLevel accessLevel, Func`2 func)
   at EPiServer.Cms.Shell.UI.Rest.Internal.ContentDataStore.GetContent(ContentReference contentReference, DefaultQueryParameters queryParameters)
   at EPiServer.Cms.Shell.UI.Rest.Internal.ContentDataStore.Get(ContentReference id, ContentReference parentLink, String[] typeIdentifiers)
   at lambda_method1693(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Mediachase.Commerce.Anonymous.Internal.AnonymousIdMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Imageflow.Server.ImageflowMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

It looks like when you use ContentReference.ID in a string the `int.ToString()` is used, which uses the `NumberFormatInfo.CurrentInfo` by default.
I guess the easy fix would be to explicitly use `ToString(NumberFormatInfo.InvariantInfo)` instead.

**Comment by mrahl** [comment]
Thanks @stefanolsen, we'll fix that too and look for other places where content IDs are turned to strings that could have the same problem. We'll get you a new build soon.

**Comment by jbearfoot** [comment]
I have now pushed new CMS Core packages 12.0.3-pre-020811 that should address the latest issue as well

**Comment by jbearfoot** [comment]
@stefanolsen Could you please confirm if the latest package solves your issues. We are about to build a 12.0.3 release and want to be sure the issues around culture and string representations in those cultures are sorted out.

**Comment by stefanolsen** [comment]
It solved the two issues I reported. Thanks.

We will test further, of course. But for now I believe you can build 12.0.3.

**Comment by jbearfoot** [comment]
Now there are 12.0.3 packages in the beta feed that solves this issue
