### ISSUE TITLE
Find: Clearing index fails

### ISSUE THREAD

**Issue by stefanolsen** [episerver/netcore-preview#131]
**Observations**
When clicking the "Clear index", the index is not being cleared. Instead the Find UI quickly shows an error modal with the following message:
```
Clear Content Index
An error occurred while clearing the content index. Refer to the detailed error message for more information.
Technical details
Unable to load /EPiServer/Find/proxy/_clear?clear_index=true&clear_stats=false status: 500
```

If I run the attempted API URL in Postman, I get this 403 error (index name is masked out):
```
{
    "status": 403,
    "error": "Your key is not authorized to access (GET) '/xxx.xxxx/_clear?timeout=20000'"
}
```

If I change the HTTP method from GET to POST, I get this "200 OK" message:
```
{
    "status": "ok"
}
```

**Expected**
The index should be cleared and ready for reindexing.

**Builds**
- EPiServer.Find.Commerce: 12.0.0-pre-00067
- EPiServer.Find.UI: 14.0.0-inte-20240

**Comment by lunchin** [comment]
I just pushed new packages that should fix this issue.  Could please try the latest Find packages on the feed

**Comment by stefanolsen** [comment]
@lunchin: I don't see any new Find packages on the feed.

**Comment by mrahl** [comment]
@stefanolsen I see you list EPiServer.Find.UI. This package is no more. Replace your reference with the latest version of EPiServer.Find.Cms (14.0.1-pre-020551 at the time of writing)

**Comment by stefanolsen** [comment]
@mrahl: I just tried removing Episerver.Find.UI ad installing the package you referred to (Episerver.Find.Commerce has no newer package available). Then I get the below exception in Startup:

```
System.AggregateException: Failed to scan some types (Failed to load types from EPiServer.Find.Commerce)
 ---> EPiServer.Framework.TypeScanner.TypeScannerReflectionException: Failed to load types from EPiServer.Find.Commerce
 ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_IconCssClass' in type 'EPiServer.Find.Commerce.EnterpriseCatalogSearchProvider' from assembly 'EPiServer.Find.Commerce, Version=11.2.0.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at EPiServer.Framework.TypeScanner.Internal.ReflectionAssemblyScanner.GetRawTypes(Assembly assembly)
   at EPiServer.Framework.TypeScanner.Internal.ReflectionAssemblyScanner.GetTypes(Assembly assembly)
System.TypeLoadException: Method 'get_IconCssClass' in type 'EPiServer.Find.Commerce.EnterpriseCatalogSearchProvider' from assembly 'EPiServer.Find.Commerce, Version=11.2.0.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7' does not have an implementation.
   --- End of inner exception stack trace ---
   at EPiServer.Framework.TypeScanner.Internal.ReflectionAssemblyScanner.GetTypes(Assembly assembly)
   at EPiServer.Framework.Initialization.Internal.InitializationEngineTypeScanner.<>c__DisplayClass3_0.<CreateLookup>b__0(Assembly assembly)
   --- End of inner exception stack trace ---
   at EPiServer.Framework.Initialization.Internal.InitializationEngineTypeScanner.CreateLookup(IEnumerable`1 assemblies, Nullable`1 maxDegreeOfParallelism)
   at EPiServer.Framework.Initialization.InitializationEngine.SetupAssemblyTypeScanner()
   at EPiServer.Framework.Initialization.InitializationEngine.BuildTypeScanner()
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddCmsHost(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddCms(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddCommerce(IServiceCollection services)
   at Site.Startup.ConfigureServices(IServiceCollection services) in C:\Repositories\Site\src\Site\Startup.cs:line 117
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Site.Program.Main(String[] args) in C:\Repositories\Site\src\Site\Program.cs:line 9
```

**Comment by mrahl** [comment]
@stefanolsen seems the Find.Commerce version on the feed is quite old, we have newer versions. My apologies, we don't have automation for publishing to the beta feed as it is temporary. I pushed the latest version now.

**Comment by stefanolsen** [comment]
@mrahl: Tried the updated package. Same error.

**Comment by mrahl** [comment]
@stefanolsen I'll add it to our internal tracker.

**Comment by mrahl** [comment]
@stefanolsen please try Find Commerce version 12.0.1-pre-000073

**Comment by lunchin** [comment]
closing this as verified clear index is working on latest versions
