### ISSUE TITLE
Exception thrown by the Event system

### ISSUE THREAD

**Issue by stefanolsen** [episerver/netcore-preview#90]
**Observations:**
When Episerver is run in a load-balanced (in this case in DXP) an exception (see below) is regularly logged.

Besides the error, it seems like Newtonsoft is still used, instead of System.Text.Json.

**Builds:**
- EPiServer.CMS.UI.Core: 12.0.0-inte-021292
- EPiServer.Commerce.Web: 14.0.0-inte-020696

**Exception data:**
```
Exception occured while raising MessageReceived for message '1065' from 'RD501AC54E4C08'
System.AggregateException: One or more errors occurred. (Type specified in JSON 'System.Linq.EmptyPartition`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Linq, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not compatible with 'System.String[], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Path 'Recipients.$type', line 1, position 282.)
 ---> Newtonsoft.Json.JsonSerializationException: Type specified in JSON 'System.Linq.EmptyPartition`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Linq, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not compatible with 'System.String[], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Path 'Recipients.$type', line 1, position 282.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at EPiServer.Shell.UI.Messaging.Internal.DefaultPushMessenger.EventRaised(Object sender, EventNotificationEventArgs e)
   at EPiServer.Events.Clients.Event.Raise(Guid raiserId, Object param, EventRaiseOption raiseOption)
   at EPiServer.Events.Clients.Event.RemoteEventReceived(Object sender, EventReceivedEventArgs e)
   at EPiServer.Events.Providers.Internal.EventProviderService.OnEventReceived(Object sender, EventReceivedEventArgs e)
   --- End of inner exception stack trace ---
   at EPiServer.Events.Providers.Internal.EventProviderService.OnEventReceived(Object sender, EventReceivedEventArgs e)
   at EPiServer.Events.Providers.EventProvider.OnMessageReceived(EventMessageEventArgs args, Boolean suppressExceptions)
```

**Comment by lunchin** [comment]
Fixed 12.0.1
